theme: jekyll-theme-minimal
#title: Potenza Drive
title: " "
name: Potenza Drive
description: Feel the pleasure of driving while experience the sound of a powerful car.
repository: Potenza Drive
show_downloads: false
logo: /assets/images/pd_logo.png

email: potenzadrive@gmail.com
